services:
  elasticsearch:
    image: elasticsearch:8.16.5
    networks:
      - 'docker-elastic'
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      'discovery.type': 'single-node'
      'http.cors.enabled': false
      'xpack.security.enabled': false

  kibana:
    image: kibana:8.16.5
    networks:
      - 'docker-elastic'
    ports:
      - '5601:5601'
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200

networks:
  docker-elastic:
    driver: bridge